# Generated by Django 2.0 on 2020-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=500)),
                ('productprice', models.IntegerField()),
                ('productdetails', models.TextField()),
            ],
        ),
    ]
