# Generated by Django 2.0 on 2020-11-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productprice',
            field=models.CharField(max_length=200),
        ),
    ]
