# Generated by Django 2.0 on 2020-11-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('ingredients', models.TextField()),
                ('Process', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='making',
            name='name',
        ),
        migrations.DeleteModel(
            name='Making',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
