# Generated by Django 2.0 on 2020-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='Process',
            field=models.TextField(),
        ),
    ]
