# Generated by Django 2.0 on 2020-11-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0002_auto_20201118_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Items_list',
        ),
    ]
